//プロフィール編集ページ
import { useSession } from "next-auth/react";
import {
  Stack,
  Box,
} from "@mui/material";
// import {ProfileTextField} from '../component/mid/profile_text_field';
import { EditContact } from "../component/mid/contact_edit";
import Header from "../component/big/header";
import Head from "next/head";
// import PageChangeButton from "@/component/Atoms/page_change_button";
import GoToLogInPage from "@/component/Templates/go_to_login_page";

export default function EditProfilePage () {
  const { data: session } = useSession();

  if (!session?.user?.user_id) {
    return <GoToLogInPage />;
  }

  return (
    <div>
      <Head>
        <title>プロフィール編集ページ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ height: "100vh" }}>
        <Header />
        <Stack
          spacing={3}
          direction="column"
          justifyContent="center"
          alignItems="center"
        >
          <EditContact student_id={session?.user.user_id} />
        </Stack>
      </Box>
    </div>
  );
};