// 求人票閲覧ページ

import Header from "@/component/big/header";
import Joblists from "@/component/big/joblist";
import Box from '@mui/material/Box';
import Head from "next/head";

export default function EditJoblistPage() {

    return (
        <div>
           <Head>
                <title>求人票閲覧ページ</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box sx={{height:'100vh'}}>
            <Header />
            <Joblists showCheckbox={false} />
            </Box>
        </div>
    );
}